tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              display: Titel
              validate:
                - required
          -
            handle: list_title
            field:
              type: text
              display: Listentitel
              instructions: 'Nur für Leuchtturmprojekte, wird benötigt für Projektliste.'
              instructions_position: below
          -
            handle: page_elements
            field:
              type: replicator
              display: Inhalt
              collapse: true
              sets:
                main_elements:
                  display: Hauptelemente
                  icon: addon-boxes-stack
                  sets:
                    image_text:
                      display: Medien/Text
                      icon: text-formatting-image-top
                      fields:
                        -
                          import: image_text_project
  archive:
    display: Werkarchiv
    sections:
      -
        fields:
          -
            handle: image
            field:
              max_files: 1
              container: assets
              folder: projekte
              type: assets
              display: Bild
          -
            handle: description
            field:
              type: textarea
              display: Beschreibung
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: project_type
            field:
              options:
                projekte: Leuchtturmprojekte
                werkarchiv: Werkarchiv
              default: werkarchiv
              type: select
              display: Typ
          -
            handle: has_detail
            field:
              type: toggle
              display: 'Detailseite?'
          -
            handle: category
            field:
              type: terms
              taxonomies:
                - category
              display: Kategorie
              mode: select
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
title: Projekte
